javac  -classpath /home/team02/phipo/DEV/java/src -deprecation -g PFrameChild.java
javac  -classpath /home/team02/phipo/DEV/java/src -deprecation -g PPAbout.java
javac  -classpath /home/team02/phipo/DEV/java/src -deprecation -g PPAppli.java
javac  -classpath /home/team02/phipo/DEV/java/src -deprecation -g PPCanvas.java
javac  -classpath /home/team02/phipo/DEV/java/src -deprecation -g PPDoubleField.java
javac  -classpath /home/team02/phipo/DEV/java/src -deprecation -g PPField.java
javac  -classpath /home/team02/phipo/DEV/java/src -deprecation -g PPFileFilter.java
javac  -classpath /home/team02/phipo/DEV/java/src -deprecation -g PPFloatField.java
javac  -classpath /home/team02/phipo/DEV/java/src -deprecation -g PPHelpChild.java
javac  -classpath /home/team02/phipo/DEV/java/src -deprecation -g PPHtml.java
javac  -classpath /home/team02/phipo/DEV/java/src -deprecation -g PPIntField.java
javac  -classpath /home/team02/phipo/DEV/java/src -deprecation -g PPManager.java
javac  -classpath /home/team02/phipo/DEV/java/src -deprecation -g PPObjectDispatch.java
javac  -classpath /home/team02/phipo/DEV/java/src -deprecation -g PPObjectDispatchClient.java
javac  -classpath /home/team02/phipo/DEV/java/src -deprecation -g PPObjectDispatcher.java
javac  -classpath /home/team02/phipo/DEV/java/src -deprecation -g PPTerm.java
javac  -classpath /home/team02/phipo/DEV/java/src -deprecation -g PPTextStream.java
javac  -classpath /home/team02/phipo/DEV/java/src -deprecation -g PPTraceTerm.java
javac  -classpath /home/team02/phipo/DEV/java/src -deprecation -g PParam.java
javac  -classpath /home/team02/phipo/DEV/java/src -deprecation -g PPrint.java
